### ISSUE TITLE
很厉害啊，请问是自学的吗？

### ISSUE THREAD

**Issue by Parfaites** [liuwenkiii/Course-Table-For-HNIT#1]
这些都是通过你的自学学会的嘛？真的很厉害啦，要向你多多学习hhh,为啥没有人提issue，我就当第一个啦

**Comment by liuwenkiii** [comment]
哈哈哈谢谢夸奖，我是看郭霖老师的第一行代码入门的，自学虽然问题比较多但是很有成就感，另外这个app还有相当多的不规范的代码（逃，打算暑假的时候再完善它
